from .ui_support import *


class MainWindowBuildMixin:
    def __init__(self):
        super().__init__()
        self.image_paths = []
        self.worker = None
        self.last_report = None
        self.last_preview_path = None
        self.setAcceptDrops(True)
        self.setWindowTitle(f"{APP_NAME} {APP_VERSION}")
        self.resize(1600, 960)
        self.setMinimumSize(1280, 800)
        self._build_ui()
        self._apply_style()
        self._wire_signals()
        self._set_default_output_dir()
        self._sync_preset()

    def _build_ui(self):
        root = QWidget()
        self.setCentralWidget(root)
        outer = QHBoxLayout(root)
        outer.setContentsMargins(0, 0, 0, 0)
        outer.setSpacing(0)

        self.sidebar = QFrame()
        self.sidebar.setObjectName("sidebar")
        self.sidebar.setFixedWidth(400)
        side = QVBoxLayout(self.sidebar)
        side.setContentsMargins(24, 24, 24, 20)
        side.setSpacing(12)

        brand = QLabel("MicroStitch Studio")
        brand.setObjectName("brand")
        subtitle = QLabel("Pathology whole-slide style image stitching")
        subtitle.setObjectName("subtitle")
        subtitle.setWordWrap(True)
        side.addWidget(brand)
        side.addWidget(subtitle)

        file_group = QGroupBox("Input images")
        file_layout = QVBoxLayout(file_group)
        button_row = QHBoxLayout()
        self.add_images_btn = QPushButton("+ Add images")
        self.add_folder_btn = QPushButton("+ Add folder")
        button_row.addWidget(self.add_images_btn)
        button_row.addWidget(self.add_folder_btn)
        file_layout.addLayout(button_row)

        self.image_list = ImageListWidget()
        self.image_list.setToolTip("Add overlapping microscope images. Drag and drop is supported.")
        self.image_list.setMinimumHeight(340)
        file_layout.addWidget(self.image_list)

        list_actions = QHBoxLayout()
        self.remove_btn = QPushButton("Remove")
        self.clear_btn = QPushButton("Clear")
        list_actions.addWidget(self.remove_btn)
        list_actions.addWidget(self.clear_btn)
        file_layout.addLayout(list_actions)
        side.addWidget(file_group, 1)

        output_group = QGroupBox("Output")
        output_layout = QVBoxLayout(output_group)
        output_row = QHBoxLayout()
        self.output_edit = QLineEdit()
        self.output_edit.setPlaceholderText("Output folder")
        self.output_edit.setToolTip("Folder where stitched PNG/TIFF previews and the JSON quality report will be written.")
        self.output_browse_btn = QPushButton("Browse")
        output_row.addWidget(self.output_edit, 1)
        output_row.addWidget(self.output_browse_btn)
        output_layout.addLayout(output_row)
        side.addWidget(output_group)

        self.stitch_btn = QPushButton("STITCH WHOLE SLIDE")
        self.stitch_btn.setObjectName("primaryButton")
        self.stitch_btn.setMinimumHeight(52)
        side.addWidget(self.stitch_btn)

        self.cancel_btn = QPushButton("Cancel")
        self.cancel_btn.setObjectName("dangerButton")
        self.cancel_btn.setEnabled(False)
        side.addWidget(self.cancel_btn)

        self.progress_bar = QProgressBar()
        self.progress_bar.setRange(0, 1000)
        self.progress_bar.setValue(0)
        self.progress_bar.setTextVisible(True)
        side.addWidget(self.progress_bar)

        self.status_label = QLabel("Ready. Add microscope images or drop them here.")
        self.status_label.setObjectName("statusLabel")
        self.status_label.setWordWrap(True)
        side.addWidget(self.status_label)

        outer.addWidget(self.sidebar)

        content = QFrame()
        content.setObjectName("content")
        content_layout = QVBoxLayout(content)
        content_layout.setContentsMargins(22, 18, 22, 18)
        content_layout.setSpacing(12)

        top_bar = QHBoxLayout()
        page_title = QLabel("Microscope Mosaic Workspace")
        page_title.setObjectName("pageTitle")
        top_bar.addWidget(page_title)
        top_bar.addStretch(1)
        self.open_result_btn = QPushButton("Open result")
        self.open_result_btn.setEnabled(False)
        self.open_folder_btn = QPushButton("Open output folder")
        self.open_folder_btn.setEnabled(False)
        top_bar.addWidget(self.open_result_btn)
        top_bar.addWidget(self.open_folder_btn)
        content_layout.addLayout(top_bar)

        metrics = QHBoxLayout()
        self.metric_images = MetricCard("Images", "0")
        self.metric_groups = MetricCard("Objective groups", "-")
        self.metric_error = MetricCard("Median registration", "-")
        self.metric_size = MetricCard("Final canvas", "-")
        metrics.addWidget(self.metric_images)
        metrics.addWidget(self.metric_groups)
        metrics.addWidget(self.metric_error)
        metrics.addWidget(self.metric_size)
        content_layout.addLayout(metrics)

        self.tabs = QTabWidget()
        content_layout.addWidget(self.tabs, 1)

        preview_tab = QWidget()
        preview_layout = QVBoxLayout(preview_tab)
        preview_layout.setContentsMargins(8, 8, 8, 8)
        preview_toolbar = QHBoxLayout()
        self.preview_name = QLabel("No result yet")
        self.preview_name.setObjectName("previewName")
        self.fit_btn = QPushButton("Fit")
        preview_toolbar.addWidget(self.preview_name)
        preview_toolbar.addStretch(1)
        preview_toolbar.addWidget(self.fit_btn)
        preview_layout.addLayout(preview_toolbar)
        self.image_view = ZoomableImageView()
        self.image_view.setObjectName("imageView")
        preview_layout.addWidget(self.image_view, 1)
        self.tabs.addTab(preview_tab, "Preview")

        settings_tab = QWidget()
        settings_layout = QVBoxLayout(settings_tab)
        settings_layout.setContentsMargins(14, 14, 14, 14)
        settings_layout.setSpacing(14)

        quality_group = QGroupBox("Processing profile")
        quality_form = QFormLayout(quality_group)
        self.preset_combo = QComboBox()
        self.preset_combo.addItems(["Fast", "Balanced", "Maximum quality", "Custom"])
        self.preset_combo.setCurrentText("Balanced")
        self.seam_combo = QComboBox()
        self.seam_combo.addItems(["graphcut", "voronoi", "crisp"])
        self.seam_combo.setCurrentText("graphcut")
        self.hybrid_check = QCheckBox("Create hybrid WSI when different objective groups are detected")
        self.hybrid_check.setChecked(False)
        self.png_check = QCheckBox("Save full-resolution PNG")
        self.png_check.setChecked(True)
        self.tiff_check = QCheckBox("Save pyramidal OME-TIFF")
        self.tiff_check.setChecked(True)
        self.preview_check = QCheckBox("Save JPEG preview")
        self.preview_check.setChecked(True)
        quality_form.addRow("Preset", self.preset_combo)
        quality_form.addRow("Seam strategy", self.seam_combo)
        quality_form.addRow("", self.hybrid_check)
        quality_form.addRow("", self.png_check)
        quality_form.addRow("", self.tiff_check)
        quality_form.addRow("", self.preview_check)
        settings_layout.addWidget(quality_group)

        advanced_group = QGroupBox("Advanced alignment")
        advanced_form = QFormLayout(advanced_group)
        self.work_dim_spin = QSpinBox()
        self.work_dim_spin.setRange(320, 1800)
        self.work_dim_spin.setSingleStep(50)
        self.work_dim_spin.setValue(750)
        self.sift_spin = QSpinBox()
        self.sift_spin.setRange(600, 12000)
        self.sift_spin.setSingleStep(200)
        self.sift_spin.setValue(2600)
        self.ratio_spin = QDoubleSpinBox()
        self.ratio_spin.setRange(0.55, 0.90)
        self.ratio_spin.setSingleStep(0.01)
        self.ratio_spin.setDecimals(2)
        self.ratio_spin.setValue(0.78)
        self.ransac_spin = QDoubleSpinBox()
        self.ransac_spin.setRange(0.5, 10.0)
        self.ransac_spin.setSingleStep(0.25)
        self.ransac_spin.setDecimals(2)
        self.ransac_spin.setValue(3.0)
        self.min_inliers_spin = QSpinBox()
        self.min_inliers_spin.setRange(6, 200)
        self.min_inliers_spin.setValue(16)
        self.blend_bands_spin = QSpinBox()
        self.blend_bands_spin.setRange(0, 8)
        self.blend_bands_spin.setValue(3)
        self.canvas_mp_spin = QDoubleSpinBox()
        self.canvas_mp_spin.setRange(20.0, 2000.0)
        self.canvas_mp_spin.setSingleStep(20.0)
        self.canvas_mp_spin.setDecimals(0)
        self.canvas_mp_spin.setValue(220.0)
        advanced_form.addRow("Feature work size (px)", self.work_dim_spin)
        advanced_form.addRow("SIFT features / image", self.sift_spin)
        advanced_form.addRow("Lowe ratio", self.ratio_spin)
        advanced_form.addRow("RANSAC threshold (px)", self.ransac_spin)
        advanced_form.addRow("Minimum inliers", self.min_inliers_spin)
        advanced_form.addRow("Blend bands", self.blend_bands_spin)
        advanced_form.addRow("Canvas safety limit (MP)", self.canvas_mp_spin)
        settings_layout.addWidget(advanced_group)
        settings_layout.addStretch(1)
        self.tabs.addTab(settings_tab, "Settings")

        log_tab = QWidget()
        log_layout = QVBoxLayout(log_tab)
        log_layout.setContentsMargins(8, 8, 8, 8)
        self.log_edit = QTextEdit()
        self.log_edit.setReadOnly(True)
        self.log_edit.setLineWrapMode(QTextEdit.NoWrap)
        self.log_edit.setToolTip("Detailed matching, optimization, rendering and export progress.")
        log_layout.addWidget(self.log_edit)
        self.tabs.addTab(log_tab, "Process log")

        outer.addWidget(content, 1)
